// log-viewer-web/src/components/StatusBadge.tsx
import type { ExecutionStatus } from '@/types/workflow-log';

const STATUS_CONFIG: Record<ExecutionStatus, { label: string; color: string }> = {
  running: { label: 'Running', color: 'var(--status-running)' },
  success: { label: 'Success', color: 'var(--status-active)' },
  failure: { label: 'Failed', color: 'var(--status-error)' },
  skipped: { label: 'Skipped', color: 'var(--status-inactive)' },
  conditionNotMet: { label: 'Condition Not Met', color: 'var(--status-inactive)' },
  cancelled: { label: 'Cancelled', color: 'var(--status-inactive)' },
};

interface StatusBadgeProps {
  status: ExecutionStatus;
}

export function StatusBadge({ status }: StatusBadgeProps) {
  const config = STATUS_CONFIG[status] ?? { label: status, color: 'var(--text-secondary)' };
  const bgColor = `color-mix(in srgb, ${config.color} 15%, transparent)`;

  return (
    <span
      className="inline-flex items-center gap-1 whitespace-nowrap uppercase"
      style={{
        backgroundColor: bgColor,
        color: config.color,
        padding: '2px 8px',
        borderRadius: 'var(--radius-full)',
        fontSize: '10px',
        fontWeight: 'var(--font-weight-bold)',
        letterSpacing: '0.03em',
        lineHeight: '1.4',
      }}
    >
      {status === 'running' && (
        <span
          className="animate-pulse-custom"
          style={{
            width: 6,
            height: 6,
            borderRadius: '50%',
            backgroundColor: 'currentColor',
          }}
        />
      )}
      {config.label}
    </span>
  );
}

// log-viewer-web/src/app/shared/components/status-badge.component.ts
import { Component, input, computed } from '@angular/core';
import { ExecutionStatus } from '../../core/models/workflow-log.model';

@Component({
  selector: 'app-status-badge',
  standalone: true,
  template: `
    <span class="badge" [style.background-color]="bgColor()" [style.color]="fgColor()">
      @if (status() === 'running') {
        <span class="dot animate-pulse"></span>
      }
      {{ label() }}
    </span>
  `,
  styles: [`
    .badge {
      display: inline-flex;
      align-items: center;
      gap: 4px;
      padding: 2px 8px;
      border-radius: var(--radius-full);
      font-size: var(--font-size-xs);
      font-weight: var(--font-weight-semibold);
      white-space: nowrap;
      line-height: 1.4;
    }
    .dot {
      width: 6px;
      height: 6px;
      border-radius: 50%;
      background-color: currentColor;
    }
  `]
})
export class StatusBadgeComponent {
  status = input.required<ExecutionStatus>();

  readonly label = computed(() => {
    const map: Record<ExecutionStatus, string> = {
      running: 'Running',
      success: 'Success',
      failure: 'Failed',
      skipped: 'Skipped',
      conditionNotMet: 'Condition Not Met',
      cancelled: 'Cancelled',
    };
    return map[this.status()] || this.status();
  });

  readonly fgColor = computed(() => {
    const map: Record<ExecutionStatus, string> = {
      running: 'var(--status-running)',
      success: 'var(--status-active)',
      failure: 'var(--status-error)',
      skipped: 'var(--status-inactive)',
      conditionNotMet: 'var(--status-warning)',
      cancelled: 'var(--status-inactive)',
    };
    return map[this.status()] || 'var(--text-secondary)';
  });

  readonly bgColor = computed(() => {
    return `color-mix(in srgb, ${this.fgColor()} 15%, transparent)`;
  });
}
