// webclient/src/features/automations/DefinitionTrigger.tsx
import { useMemo, useState, useCallback } from 'react';
import { Icon } from '@/components/Icon';
import { useDeviceRegistry } from '@/contexts/DeviceRegistryContext';
import { useConfig } from '@/contexts/ConfigContext';
import type {
  AutomationTriggerDef, DeviceStateTriggerDef,
  ScheduleTriggerDef, SunEventTriggerDef, WebhookTriggerDef,
} from '@/types/automation-definition';
import { TRIGGER_TYPE_ICONS } from '@/types/automation-log';
import { formatTriggerCondition, formatScheduleType, formatRetriggerPolicy } from '@/utils/automation-definition-utils';
import './tree-common.css';

interface DefinitionTriggerProps {
  trigger: AutomationTriggerDef;
  depth?: number;
}

export function DefinitionTrigger({ trigger, depth = 0 }: DefinitionTriggerProps) {
  const registry = useDeviceRegistry();
  const { baseUrl } = useConfig();
  const [copied, setCopied] = useState(false);

  const copyUrl = useCallback((text: string) => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, []);

  const triggerIcon = TRIGGER_TYPE_ICONS[trigger.type] || 'bolt-circle-fill';

  const displayName = useMemo(() => {
    if (trigger.name) return trigger.name;
    switch (trigger.type) {
      case 'deviceStateChange': {
        const d = trigger as DeviceStateTriggerDef;
        return registry.lookupDevice(d.deviceId)?.name || d.deviceId;
      }
      case 'schedule': return 'Schedule';
      case 'webhook': return 'Webhook';
      case 'automation': return 'Callable Trigger';
      case 'sunEvent': {
        const s = trigger as SunEventTriggerDef;
        return s.event === 'sunrise' ? 'Sunrise' : 'Sunset';
      }
      default: return (trigger as AutomationTriggerDef).type;
    }
  }, [trigger, registry]);

  const detailText = useMemo(() => {
    switch (trigger.type) {
      case 'deviceStateChange': {
        const d = trigger as DeviceStateTriggerDef;
        const device = registry.lookupDevice(d.deviceId);
        const char = registry.lookupCharacteristic(d.deviceId, d.characteristicId);
        const charLabel = char?.name || d.characteristicId;
        const parts: string[] = [];
        if (device?.room) parts.push(device.room);
        parts.push(`${charLabel} ${formatTriggerCondition(d.condition)}`);
        return parts.join(' · ');
      }
      case 'schedule': {
        const s = trigger as ScheduleTriggerDef;
        return formatScheduleType(s.scheduleType);
      }
      case 'webhook': {
        const w = trigger as WebhookTriggerDef;
        return `Token: ${w.token}`;
      }
      case 'sunEvent': {
        const s = trigger as SunEventTriggerDef;
        if (s.offsetMinutes === 0) return undefined;
        const abs = Math.abs(s.offsetMinutes);
        const dir = s.offsetMinutes > 0 ? 'after' : 'before';
        return `${abs} min ${dir}`;
      }
      case 'automation': return 'Can be triggered by other automations';
      default: return undefined;
    }
  }, [trigger, registry]);

  const retriggerLabel = useMemo(() => {
    const policy = (trigger as { retriggerPolicy?: string }).retriggerPolicy;
    if (!policy) return null;
    return formatRetriggerPolicy(policy);
  }, [trigger]);

  return (
    <div className="tree-node">

      <div className="tree-row" style={{ paddingLeft: depth * 20 }}>
        <span className="tree-chevron-spacer" />
        <span className="tree-icon" style={{ color: 'var(--tint-main)' }}>
          <Icon name={triggerIcon} size={16} />
        </span>

        <div className="tree-info">
          <span className="tree-name">{displayName}</span>
        </div>
      </div>

      {detailText && (
        <div className="tree-trigger-details" style={{ paddingLeft: depth * 20 + 18, display: 'flex', alignItems: 'center', gap: 6 }}>
          <span className="tree-detail">{detailText}</span>
          {trigger.type === 'webhook' && (trigger as WebhookTriggerDef).token && (
            <button
              type="button"
              style={{ background: 'none', border: 'none', padding: 0, cursor: 'pointer', color: copied ? 'var(--status-active)' : 'var(--text-tertiary)', display: 'inline-flex', flexShrink: 0 }}
              onClick={() => copyUrl(`${baseUrl}/automations/webhook/${(trigger as WebhookTriggerDef).token}`)}
              title="Copy webhook URL"
            >
              <Icon name={copied ? 'checkmark' : 'doc-on-doc'} size={16} />
            </button>
          )}
        </div>
      )}

      {(retriggerLabel || (trigger.conditions && trigger.conditions.length > 0)) && (
        <div style={{ paddingLeft: depth * 20 + 18, display: 'flex', flexWrap: 'wrap', gap: 4, marginTop: 2 }}>
          {retriggerLabel && (
            <span className="retrigger-badge">
              <Icon name="repeat" size={12} className="retrigger-badge-icon" />
              {retriggerLabel}
            </span>
          )}
          {trigger.conditions && trigger.conditions.length > 0 && (() => {
            const conds = trigger.conditions!;
            return (
              <span className="retrigger-badge" style={{ borderColor: 'var(--tint-secondary)', color: 'var(--tint-secondary)' }}>
                <Icon name="shield" size={12} className="retrigger-badge-icon" />
                {conds.length === 1 && conds[0]?.type === 'and'
                  ? `${(conds[0] as { conditions?: unknown[] }).conditions?.length ?? 0} condition(s)`
                  : `${conds.length} condition(s)`
                }
              </span>
            );
          })()}
        </div>
      )}
    </div>
  );
}

// log-viewer-web/src/app/features/workflows/components/definition-trigger.component.ts
import { Component, input, computed, inject, signal } from '@angular/core';
import {
  WorkflowTriggerDef, CompoundTriggerDef, DeviceStateTriggerDef,
  ScheduleTriggerDef, SunEventTriggerDef, WebhookTriggerDef,
} from '../../../core/models/workflow-definition.model';
import { TRIGGER_TYPE_ICONS } from '../../../core/models/workflow-log.model';
import { formatTriggerCondition, formatScheduleType, formatRetriggerPolicy } from '../../../core/utils/workflow-definition-utils';
import { IconComponent } from '../../../shared/components/icon.component';
import { DeviceRegistryService } from '../../../core/services/device-registry.service';

const DEPTH_COLORS = [
  'var(--depth-0)',
  'var(--depth-1)',
  'var(--depth-2)',
  'var(--depth-3)',
  'var(--depth-4)',
];

@Component({
  selector: 'app-definition-trigger',
  standalone: true,
  imports: [IconComponent, DefinitionTriggerComponent],
  template: `
    <div class="trigger-node">
      <div class="trigger-row" [class.collapsible]="hasChildren()" (click)="toggle()">
        @for (i of depthRange(); track i) {
          <div class="connector-line" [style.background-color]="depthColor(i)"></div>
        }

        @if (hasChildren()) {
          <span class="chevron" [class.collapsed]="collapsed()">
            <app-icon name="chevron-down" [size]="12" />
          </span>
        }

        <span class="trigger-icon" [style.color]="iconColor()">
          <app-icon [name]="triggerIcon()" [size]="16" />
        </span>

        @if (trigger().type === 'compound') {
          <span class="logic-badge">{{ operatorLabel() }}</span>
        }

        <div class="trigger-info">
          <span class="trigger-name">{{ displayName() }}</span>
          @if (detailText()) {
            <span class="trigger-detail">{{ detailText() }}</span>
          }
          @if (retriggerLabel()) {
            <span class="retrigger-badge">
              <span class="retrigger-badge-key">Retrigger</span>
              {{ retriggerLabel() }}
            </span>
          }
          @if (collapsed() && hasChildren()) {
            <span class="collapsed-hint">{{ compoundTriggers().length }} nested</span>
          }
        </div>
      </div>

      @if (!collapsed() && trigger().type === 'compound') {
        @for (sub of compoundTriggers(); track $index) {
          <app-definition-trigger [trigger]="sub" [depth]="depth() + 1" />
        }
      }
    </div>
  `,
  styles: [`
    .trigger-node {
      font-size: var(--font-size-sm);
    }
    .trigger-row {
      display: flex;
      align-items: flex-start;
      gap: 6px;
      padding: 6px 0;
    }
    .connector-line {
      width: 2px;
      min-height: 24px;
      align-self: stretch;
      opacity: 0.3;
      border-radius: 1px;
      flex-shrink: 0;
      margin-left: 6px;
    }
    .trigger-icon {
      display: flex;
      align-items: center;
      flex-shrink: 0;
      margin-top: 1px;
    }
    .logic-badge {
      font-size: var(--font-size-xs);
      font-weight: var(--font-weight-bold);
      padding: 1px 6px;
      border-radius: 4px;
      background: color-mix(in srgb, var(--tint-secondary) 15%, transparent);
      color: var(--tint-secondary);
      text-transform: uppercase;
      flex-shrink: 0;
    }
    .trigger-info {
      flex: 1;
      min-width: 0;
      display: flex;
      flex-direction: column;
      gap: 2px;
    }
    .trigger-name {
      font-weight: var(--font-weight-semibold);
      color: var(--text-primary);
    }
    .trigger-detail {
      color: var(--text-secondary);
      line-height: 1.4;
    }
    .retrigger-badge {
      display: inline-flex;
      align-items: center;
      align-self: flex-start;
      gap: 4px;
      font-size: 10px;
      font-weight: var(--font-weight-medium);
      padding: 2px 8px;
      border-radius: var(--radius-full);
      background: color-mix(in srgb, var(--text-tertiary) 10%, transparent);
      color: var(--text-secondary);
      margin-top: 2px;
    }
    .retrigger-badge-key {
      font-weight: var(--font-weight-bold);
      color: var(--text-tertiary);
      text-transform: uppercase;
      font-size: 9px;
      letter-spacing: 0.06em;
    }
    .trigger-row.collapsible { cursor: pointer; border-radius: var(--radius-xs); }
    .trigger-row.collapsible:hover { background: color-mix(in srgb, var(--text-tertiary) 6%, transparent); }
    .chevron {
      display: flex;
      align-items: center;
      flex-shrink: 0;
      color: var(--text-tertiary);
      transition: transform 0.15s ease;
      margin-top: 1px;
    }
    .chevron.collapsed { transform: rotate(-90deg); }
    .collapsed-hint {
      font-size: var(--font-size-xs);
      color: var(--text-tertiary);
      font-style: italic;
    }
  `]
})
export class DefinitionTriggerComponent {
  private registry = inject(DeviceRegistryService);

  trigger = input.required<WorkflowTriggerDef>();
  depth = input(0);
  collapsed = signal(false);

  readonly depthRange = computed(() => Array.from({ length: this.depth() }, (_, i) => i));
  readonly hasChildren = computed(() => this.compoundTriggers().length > 0);

  toggle(): void {
    if (this.hasChildren()) this.collapsed.update(v => !v);
  }

  readonly triggerIcon = computed(() => {
    return TRIGGER_TYPE_ICONS[this.trigger().type] || 'bolt-circle-fill';
  });

  readonly iconColor = computed(() => {
    return 'var(--tint-main)';
  });

  readonly operatorLabel = computed(() => {
    const t = this.trigger();
    if (t.type === 'compound') return (t as CompoundTriggerDef).operator.toUpperCase();
    return '';
  });

  readonly displayName = computed(() => {
    const t = this.trigger();
    if (t.name) return t.name;
    switch (t.type) {
      case 'deviceStateChange': {
        const d = t as DeviceStateTriggerDef;
        return this.registry.lookupDevice(d.deviceId)?.name || d.deviceId;
      }
      case 'schedule': return 'Schedule';
      case 'webhook': return 'Webhook';
      case 'compound': return 'Compound Trigger';
      case 'workflow': return 'Callable Trigger';
      case 'sunEvent': {
        const s = t as SunEventTriggerDef;
        return s.event === 'sunrise' ? 'Sunrise' : 'Sunset';
      }
      default: return (t as any).type;
    }
  });

  readonly detailText = computed(() => {
    const t = this.trigger();
    switch (t.type) {
      case 'deviceStateChange': {
        const d = t as DeviceStateTriggerDef;
        const device = this.registry.lookupDevice(d.deviceId);
        const char = this.registry.lookupCharacteristic(d.deviceId, d.characteristicId);
        const charLabel = char?.name || d.characteristicId;
        const parts: string[] = [];
        if (device?.room) parts.push(device.room);
        parts.push(`${charLabel} ${formatTriggerCondition(d.condition)}`);
        return parts.join(' · ');
      }
      case 'schedule': {
        const s = t as ScheduleTriggerDef;
        return formatScheduleType(s.scheduleType);
      }
      case 'webhook': {
        const w = t as WebhookTriggerDef;
        return `Token: ${w.token}`;
      }
      case 'sunEvent': {
        const s = t as SunEventTriggerDef;
        if (s.offsetMinutes === 0) return undefined;
        const abs = Math.abs(s.offsetMinutes);
        const dir = s.offsetMinutes > 0 ? 'after' : 'before';
        return `${abs} min ${dir}`;
      }
      case 'compound': return undefined;
      case 'workflow': return 'Can be triggered by other workflows';
      default: return undefined;
    }
  });

  readonly retriggerLabel = computed(() => {
    const policy = (this.trigger() as any).retriggerPolicy;
    if (!policy) return null;
    return formatRetriggerPolicy(policy);
  });

  readonly compoundTriggers = computed(() => {
    const t = this.trigger();
    if (t.type === 'compound') return (t as CompoundTriggerDef).triggers;
    return [];
  });

  depthColor(i: number): string {
    return DEPTH_COLORS[i % DEPTH_COLORS.length];
  }
}
