// log-viewer-web/src/features/workflows/WorkflowCard.tsx
import { memo, useMemo, useRef, useCallback } from 'react';
import { Icon } from '@/components/Icon';
import type { Workflow, TriggerTypeKey } from '@/types/workflow-log';
import { TRIGGER_TYPE_LABELS, TRIGGER_TYPE_ICONS } from '@/types/workflow-log';
import { relativeTime } from '@/utils/date-utils';
import './WorkflowCard.css';

interface WorkflowCardProps {
  workflow: Workflow;
  index?: number;
  onToggleEnabled: (workflowId: string, enabled: boolean) => void;
  onDelete: (workflowId: string) => void;
  onClick: (workflowId: string) => void;
  selectionMode?: boolean;
  isSelected?: boolean;
  onSelect?: (workflowId: string) => void;
  onLongPress?: (workflowId: string) => void;
}

const SWIPE_THRESHOLD = 80;
const LONG_PRESS_DELAY = 500;

export const WorkflowCard = memo(function WorkflowCard({
  workflow,
  index = 0,
  onToggleEnabled,
  onDelete,
  onClick,
  selectionMode = false,
  isSelected = false,
  onSelect,
  onLongPress,
}: WorkflowCardProps) {
  const triggerType: TriggerTypeKey = workflow.triggers.length > 0
    ? (workflow.triggers[0]?.type ?? 'deviceStateChange')
    : 'deviceStateChange';

  const triggerIcon = TRIGGER_TYPE_ICONS[triggerType];
  const triggerLabel = TRIGGER_TYPE_LABELS[triggerType];

  const statusColor = useMemo(() => {
    if (!workflow.isEnabled) return 'var(--status-inactive)';
    if (workflow.metadata.consecutiveFailures > 0) return 'var(--status-error)';
    if (workflow.metadata.totalExecutions > 0) return 'var(--status-active)';
    return 'var(--tint-main)';
  }, [workflow.isEnabled, workflow.metadata.consecutiveFailures, workflow.metadata.totalExecutions]);

  const statusBg = `color-mix(in srgb, ${statusColor} 15%, transparent)`;
  const pillBg = `color-mix(in srgb, ${statusColor} 12%, transparent)`;

  // Swipe state refs (no re-renders needed during gesture)
  const containerRef = useRef<HTMLDivElement>(null);
  const cardRef = useRef<HTMLDivElement>(null);
  const startXRef = useRef(0);
  const currentXRef = useRef(0);
  const swipingRef = useRef(false);
  const longPressTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const didLongPressRef = useRef(false);

  const clearLongPress = useCallback(() => {
    if (longPressTimerRef.current) {
      clearTimeout(longPressTimerRef.current);
      longPressTimerRef.current = null;
    }
  }, []);

  const handleTouchStart = useCallback((e: React.TouchEvent) => {
    if (selectionMode) return;
    const touch = e.touches[0]!;
    startXRef.current = touch.clientX;
    currentXRef.current = 0;
    swipingRef.current = false;
    didLongPressRef.current = false;

    // Start long-press timer
    longPressTimerRef.current = setTimeout(() => {
      didLongPressRef.current = true;
      onLongPress?.(workflow.id);
      // Vibrate if available
      if (navigator.vibrate) navigator.vibrate(30);
    }, LONG_PRESS_DELAY);
  }, [selectionMode, onLongPress, workflow.id]);

  const handleTouchMove = useCallback((e: React.TouchEvent) => {
    if (selectionMode) return;
    const touch = e.touches[0]!;
    const diff = startXRef.current - touch.clientX;

    // If moving, cancel long press
    if (Math.abs(diff) > 10) {
      clearLongPress();
    }

    if (diff > 10) {
      if (!swipingRef.current) containerRef.current?.classList.add('swiping');
      swipingRef.current = true;
      // Apply resistance after threshold
      const capped = Math.min(diff, SWIPE_THRESHOLD * 1.8);
      currentXRef.current = capped;
      if (cardRef.current) {
        cardRef.current.style.transform = `translateX(${-capped}px)`;
        cardRef.current.style.transition = 'none';
      }
    } else if (diff < -10 && swipingRef.current) {
      // Swiping back
      currentXRef.current = 0;
      if (cardRef.current) {
        cardRef.current.style.transform = 'translateX(0)';
        cardRef.current.style.transition = 'none';
      }
    }
  }, [selectionMode, clearLongPress]);

  const handleTouchEnd = useCallback(() => {
    clearLongPress();
    if (selectionMode) return;

    if (swipingRef.current && currentXRef.current >= SWIPE_THRESHOLD) {
      // Trigger delete confirmation
      if (cardRef.current) {
        cardRef.current.style.transition = 'transform 200ms ease';
        cardRef.current.style.transform = 'translateX(0)';
      }
      onDelete(workflow.id);
    } else if (swipingRef.current) {
      // Snap back
      if (cardRef.current) {
        cardRef.current.style.transition = 'transform 200ms ease';
        cardRef.current.style.transform = 'translateX(0)';
      }
    }
    swipingRef.current = false;
    currentXRef.current = 0;
    containerRef.current?.classList.remove('swiping');
  }, [selectionMode, onDelete, clearLongPress, workflow.id]);

  const handleClick = useCallback(() => {
    if (didLongPressRef.current) return;
    if (selectionMode) {
      onSelect?.(workflow.id);
    } else {
      onClick(workflow.id);
    }
  }, [selectionMode, onSelect, onClick, workflow.id]);

  const handleToggle = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    onToggleEnabled(workflow.id, e.target.checked);
  }, [onToggleEnabled, workflow.id]);

  return (
    <div ref={containerRef} className="wf-card-swipe-container">
      {/* Delete action revealed behind the card */}
      <div className="wf-swipe-action-delete">
        <Icon name="trash" size={18} />
        <span>Delete</span>
      </div>

      <div
        ref={cardRef}
        className={`wf-card animate-card-enter${selectionMode ? ' selection-mode' : ''}${isSelected ? ' selected' : ''}`}
        style={{ animationDelay: `${index * 40}ms` }}
        onClick={handleClick}
        onTouchStart={handleTouchStart}
        onTouchMove={handleTouchMove}
        onTouchEnd={handleTouchEnd}
      >
        {selectionMode && (
          <div className="wf-select-check">
            <div className={`wf-checkbox${isSelected ? ' checked' : ''}`}>
              {isSelected && <Icon name="checkmark" size={12} />}
            </div>
          </div>
        )}

        <div className="wf-trigger-icon" style={{ color: statusColor }}>
          <div className="wf-trigger-icon-bg" style={{ background: statusBg }}>
            <Icon name={triggerIcon} size={18} />
          </div>
        </div>

        <div className="wf-content">
          <div className="wf-name-row">
            <span className="wf-name">{workflow.name}</span>
            {!workflow.isEnabled && <span className="wf-disabled-badge">Disabled</span>}
          </div>

          <div className="wf-stats-row">
            <span className="wf-trigger-pill" style={{ color: statusColor, background: pillBg }}>
              {triggerLabel}
            </span>
            <span className="wf-stat">
              <Icon name="bolt-circle-fill" size={12} />
              {workflow.triggers.length}
            </span>
            <span className="wf-stat">
              <Icon name="rectangles-group" size={12} />
              {workflow.blocks.length}
            </span>
            {workflow.metadata.totalExecutions > 0 && (
              <span className="wf-stat">
                <Icon name="play-circle-fill" size={12} />
                {workflow.metadata.totalExecutions}
              </span>
            )}
          </div>

          {workflow.description && (
            <div className="wf-description">{workflow.description}</div>
          )}

          {workflow.metadata.lastTriggeredAt && (
            <div className="wf-last-triggered">
              Last triggered {relativeTime(workflow.metadata.lastTriggeredAt)}
            </div>
          )}
        </div>

        {!selectionMode && (
          <div className="wf-right-actions" onClick={e => e.stopPropagation()}>
            <label className="wf-toggle-wrapper">
              <input
                type="checkbox"
                checked={workflow.isEnabled}
                onChange={handleToggle}
              />
              <span className="wf-toggle-track" />
            </label>
          </div>
        )}
      </div>
    </div>
  );
});

// log-viewer-web/src/app/features/workflows/components/workflow-card.component.ts
import { Component, input, output, computed } from '@angular/core';
import { Workflow, TriggerTypeKey, TRIGGER_TYPE_LABELS, TRIGGER_TYPE_ICONS } from '../../../core/models/workflow-log.model';
import { IconComponent } from '../../../shared/components/icon.component';
import { RelativeTimePipe } from '../../../shared/pipes/relative-time.pipe';

@Component({
  selector: 'app-workflow-card',
  standalone: true,
  imports: [IconComponent, RelativeTimePipe],
  template: `
    <div class="workflow-card" [style.animation-delay.ms]="index() * 40">
      <!-- Trigger icon circle -->
      <div class="trigger-icon" [style.color]="statusColor()">
        <div class="trigger-icon-bg" [style.background]="statusBg()">
          <app-icon [name]="triggerIcon()" [size]="18" />
        </div>
      </div>

      <!-- Content -->
      <div class="content">
        <!-- Row 1: Name + disabled badge -->
        <div class="name-row">
          <span class="workflow-name">{{ workflow().name }}</span>
          @if (!workflow().isEnabled) {
            <span class="disabled-badge">Disabled</span>
          }
        </div>

        <!-- Row 2: Trigger type pill + stats -->
        <div class="stats-row">
          <span class="trigger-pill" [style.color]="statusColor()" [style.background]="pillBg()">
            {{ triggerLabel() }}
          </span>
          <span class="stat">
            <app-icon name="bolt-circle-fill" [size]="12" />
            {{ workflow().triggers.length }}
          </span>
          <span class="stat">
            <app-icon name="rectangles-group" [size]="12" />
            {{ workflow().blocks.length }}
          </span>
          @if (workflow().metadata.totalExecutions > 0) {
            <span class="stat">
              <app-icon name="play-circle-fill" [size]="12" />
              {{ workflow().metadata.totalExecutions }}
            </span>
          }
        </div>

        <!-- Row 3: Description -->
        @if (workflow().description) {
          <div class="description">{{ workflow().description }}</div>
        }

        <!-- Row 4: Last triggered -->
        @if (workflow().metadata.lastTriggeredAt) {
          <div class="last-triggered">
            Last triggered {{ workflow().metadata.lastTriggeredAt! | relativeTime }}
          </div>
        }
      </div>

      <!-- Actions: delete + toggle -->
      <div class="right-actions" (click)="$event.stopPropagation()">
        <button class="delete-btn" (click)="deleteRequested.emit()" title="Delete workflow">
          <app-icon name="trash" [size]="15" />
        </button>
        <label class="toggle-wrapper">
          <input
            type="checkbox"
            [checked]="workflow().isEnabled"
            (change)="onToggleChange($event)"
          />
          <span class="toggle-track"></span>
        </label>
      </div>
    </div>
  `,
  styles: [`
    :host {
      display: block;
      animation: cardEnter 350ms cubic-bezier(0, 0, 0.2, 1) backwards;
    }
    .workflow-card {
      display: flex;
      align-items: flex-start;
      gap: var(--spacing-sm);
      padding: var(--card-padding);
      background: var(--bg-card);
      border-radius: var(--radius-md);
      border: none;
      box-shadow: var(--shadow-card);
      margin-bottom: var(--card-gap);
      cursor: pointer;
      transition: background 150ms ease, box-shadow 150ms ease, transform 150ms cubic-bezier(0.34, 1.56, 0.64, 1);
    }
    .workflow-card:hover {
      box-shadow: var(--shadow-card-hover);
    }

    /* Trigger icon */
    .trigger-icon {
      flex-shrink: 0;
      padding-top: 2px;
    }
    .trigger-icon-bg {
      width: 36px;
      height: 36px;
      border-radius: 50%;
      display: flex;
      align-items: center;
      justify-content: center;
    }

    /* Content */
    .content {
      flex: 1;
      min-width: 0;
      padding-top: 2px;
    }
    .name-row {
      display: flex;
      align-items: center;
      gap: var(--spacing-xs);
      flex-wrap: wrap;
    }
    .workflow-name {
      font-size: var(--font-size-base);
      font-weight: var(--font-weight-bold);
      color: var(--text-primary);
    }
    .disabled-badge {
      font-size: var(--font-size-xs);
      font-weight: var(--font-weight-medium);
      padding: 1px 6px;
      border-radius: 4px;
      background: var(--bg-pill);
      color: var(--text-secondary);
    }

    /* Stats row */
    .stats-row {
      display: flex;
      align-items: center;
      gap: var(--spacing-sm);
      margin-top: 4px;
      flex-wrap: wrap;
    }
    .trigger-pill {
      font-size: var(--font-size-xs);
      font-weight: var(--font-weight-medium);
      padding: 1px 6px;
      border-radius: 4px;
    }
    .stat {
      display: inline-flex;
      align-items: center;
      gap: 3px;
      font-size: var(--font-size-xs);
      color: var(--text-secondary);
    }

    /* Description */
    .description {
      font-size: var(--font-size-sm);
      color: var(--text-secondary);
      margin-top: 4px;
      overflow: hidden;
      text-overflow: ellipsis;
      white-space: nowrap;
    }

    /* Last triggered */
    .last-triggered {
      font-size: var(--font-size-xs);
      color: var(--text-tertiary);
      margin-top: 4px;
    }

    /* Right actions */
    .right-actions {
      flex-shrink: 0;
      display: flex;
      align-items: flex-start;
      gap: var(--spacing-xs);
      padding-top: 4px;
    }
    .delete-btn {
      display: flex;
      align-items: center;
      justify-content: center;
      width: 30px;
      height: 30px;
      border-radius: var(--radius-xs);
      border: none;
      background: none;
      cursor: pointer;
      color: var(--status-error);
      opacity: 0;
      transition: opacity var(--transition-fast), background var(--transition-fast);
      font-family: inherit;
    }
    .workflow-card:hover .delete-btn { opacity: 0.6; }
    .delete-btn:hover { opacity: 1 !important; background: color-mix(in srgb, var(--status-error) 10%, transparent); }

    /* Toggle switch */
    .toggle-wrapper {
      flex-shrink: 0;
      position: relative;
      display: inline-flex;
      align-items: center;
      cursor: pointer;
      padding-top: 3px;
    }
    .toggle-wrapper input {
      position: absolute;
      opacity: 0;
      width: 0;
      height: 0;
    }
    .toggle-track {
      width: 42px;
      height: 24px;
      border-radius: 12px;
      background: var(--bg-pill);
      position: relative;
      transition: background 200ms ease;
    }
    .toggle-track::before {
      content: '';
      position: absolute;
      top: 2px;
      left: 2px;
      width: 20px;
      height: 20px;
      border-radius: 50%;
      background: white;
      box-shadow: 0 1px 3px rgba(0, 0, 0, 0.2);
      transition: transform 200ms ease;
    }
    .toggle-wrapper input:checked + .toggle-track {
      background: var(--tint-main);
    }
    .toggle-wrapper input:checked + .toggle-track::before {
      transform: translateX(18px);
    }

    /* Responsive */
    @media (max-width: 768px) {
      .workflow-card {
        --card-padding: 12px;
        border-radius: var(--radius-sm);
        gap: var(--spacing-xs);
      }
      .workflow-name {
        font-size: var(--font-size-sm);
      }
    }
    @media (max-width: 480px) {
      .stats-row {
        gap: var(--spacing-xs);
      }
    }
  `]
})
export class WorkflowCardComponent {
  workflow = input.required<Workflow>();
  index = input(0);
  toggleEnabled = output<boolean>();
  deleteRequested = output<void>();

  readonly triggerType = computed((): TriggerTypeKey => {
    const triggers = this.workflow().triggers;
    return triggers.length > 0 ? triggers[0].type : 'deviceStateChange';
  });

  readonly triggerIcon = computed(() => TRIGGER_TYPE_ICONS[this.triggerType()]);
  readonly triggerLabel = computed(() => TRIGGER_TYPE_LABELS[this.triggerType()]);

  readonly statusColor = computed(() => {
    const wf = this.workflow();
    if (!wf.isEnabled) return 'var(--status-inactive)';
    if (wf.metadata.consecutiveFailures > 0) return 'var(--status-error)';
    if (wf.metadata.totalExecutions > 0) return 'var(--status-active)';
    return 'var(--tint-main)';
  });

  readonly statusBg = computed(() => {
    return `color-mix(in srgb, ${this.statusColor()} 15%, transparent)`;
  });

  readonly pillBg = computed(() => {
    return `color-mix(in srgb, ${this.statusColor()} 12%, transparent)`;
  });

  onToggleChange(event: Event): void {
    const checked = (event.target as HTMLInputElement).checked;
    this.toggleEnabled.emit(checked);
  }
}
